Repository woowa-techcamp-2022/web-fleemarket-08, pull requests merged in 2022-08, with the labels that each got.

#2 [Setup] setup: 이슈 템플릿, PR 템플릿 추가
  .github/ISSUE_TEMPLATE/basic-template.md
  .github/ISSUE_TEMPLATE/bug-report-template.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: setup, Pair

#4 [Setup] 프론트엔드, 백엔드 기본 파일 설치
  .prettierrc
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.tsx
  client/src/index.tsx
  client/src/react-app-env.d.ts
  client/src/setupTests.ts
  client/tsconfig.json
  server/.eslintrc.js
  server/.gitignore
  server/nest-cli.json
  server/package-lock.json
  server/package.json
  server/src/app.controller.ts
  server/src/app.module.ts
  server/src/app.service.ts
  server/src/main.ts
  server/tsconfig.build.json
  server/tsconfig.json
Labels: frontend, setup, Pair, backend

#9 [Feature] 아이콘 추가 및 색상 변수 설정
  .github/PULL_REQUEST_TEMPLATE.md
  client/src/assets/icons/add.svg
  client/src/assets/icons/category.svg
  client/src/assets/icons/check.svg
  client/src/assets/icons/chevron-down.svg
  client/src/assets/icons/chevron-left.svg
  client/src/assets/icons/chevron-right.svg
  client/src/assets/icons/close.svg
  client/src/assets/icons/heart.svg
  client/src/assets/icons/image.svg
  client/src/assets/icons/index.ts
  client/src/assets/icons/log-out.svg
  client/src/assets/icons/map-pin.svg
  client/src/assets/icons/menu.svg
  client/src/assets/icons/message-square.svg
  client/src/assets/icons/more-vertical.svg
  client/src/assets/icons/send.svg
  client/src/assets/icons/user.svg
  client/src/constants/colors.ts
Labels: feature, frontend, Pair

#10 [Feature] user region api 구조 설정
  server/package-lock.json
  server/package.json
  server/src/category/entities/category.entity.ts
  server/src/chat/chat.controller.ts
  server/src/main.ts
  server/src/user/dto/create-user-region.dto.ts
  server/src/user/dto/create-user.dto.ts
  server/src/user/dto/update-user.dto.ts
  server/src/user/user.controller.ts
  server/src/user/user.service.ts
Labels: feature, Pair, backend

#12 [Feature] region, product swagger API 명세 작성
  server/src/product/dto/create-product.dto.ts
  server/src/product/dto/product.dto.ts
  server/src/product/dto/update-product.dto.ts
  server/src/product/entities/product.entity.ts
  server/src/product/product.controller.ts
  server/src/product/product.service.ts
  server/src/region/dto/create-region.dto.ts
  server/src/region/dto/update-region.dto.ts
  server/src/region/region.controller.ts
  server/src/region/region.service.ts
Labels: feature, backend

#14 [Feature] GitHub OAuth 로그인
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/api/index.ts
  client/src/index.tsx
  client/src/pages/Home.tsx
  client/src/pages/SocialLogin.tsx
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/main.ts
  server/src/social-login/entities/social-login.entity.ts
  server/src/social-login/social-login.service.ts
  server/src/types/index.ts
  server/src/user/entities/user.entity.ts
Labels: feature, frontend, backend

#16 [Feat] Category API 구현
  server/sql/init-category.sql
  server/src/app.module.ts
  server/src/category/category.service.ts
  server/src/category/entities/category.entity.ts
Labels: feature, backend

#18 [Feature] Region API 구현
  server/sql/init.sql
  server/src/region/entities/region.entity.ts
  server/src/region/region.service.ts
  server/src/user/dto/create-user-region.dto.ts
  server/src/user/entities/user-region.entity.ts
  server/src/user/user.controller.ts
  server/src/user/user.service.ts
Labels: feature, backend

#24 [Feature] Chat API 구현
  server/src/app.module.ts
  server/src/chat/chat.controller.ts
  server/src/chat/chat.module.ts
  server/src/chat/chat.service.ts
  server/src/chat/dto/create-chat.dto.ts
  server/src/chat/entities/chat-content.entity.ts
  server/src/chat/entities/chat-room.entity.ts
  server/src/product/entities/product.entity.ts
Labels: feature, backend

#22 [Feature] Product API 구현
  server/src/chat/entities/chat-content.entity.ts
  server/src/chat/entities/chat-room.entity.ts
  server/src/product/dto/product.dto.ts
  server/src/product/entities/product-image.entity.ts
  server/src/product/entities/product-like.entity.ts
  server/src/product/entities/product.entity.ts
  server/src/product/product.controller.ts
  server/src/product/product.module.ts
  server/src/product/product.service.ts
  server/src/user/entities/user.entity.ts
Labels: feature, backend

#30 [Feature] 페이지 컴포넌트 생성 및 라우팅 연결
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/assets/icons/index.ts
  client/src/components/ProductItem.tsx
  client/src/components/Unauthorized.tsx
  client/src/components/common/Header.tsx
  client/src/components/main/MainHeader.tsx
  client/src/components/menu/Chat.tsx
  client/src/components/menu/SalesList.tsx
  client/src/components/menu/WishList.tsx
  client/src/pages/Category.tsx
  client/src/pages/Chat.tsx
  client/src/pages/ChatContent.tsx
  client/src/pages/Home.tsx
  client/src/pages/Login.tsx
  client/src/pages/MyPage.tsx
  client/src/pages/NotFound.tsx
  client/src/pages/Product.tsx
  client/src/pages/Profile.tsx
  client/src/pages/Region.tsx
  client/src/pages/Write.tsx
  client/src/recoil/atoms/user.ts
Labels: feature, frontend, pair

#31 [Feature] Product Like API 구현
  server/src/app.controller.ts
  server/src/app.module.ts
  server/src/app.service.ts
  server/src/product/product.controller.ts
  server/src/product/product.service.ts
Labels: feature, backend

#32 [Feature] 프론트엔드 api 요청 함수 작성 및 DTO, 응답 타입 정의
  .prettierrc
  client/src/api/index.ts
  client/src/types/dto.ts
  client/src/types/index.ts
  server/src/chat/chat.controller.ts
  server/src/chat/chat.service.ts
  server/src/chat/dto/create-chat-content.dto.ts
  server/src/chat/dto/create-chat-room.dto.ts
  server/src/product/product.service.ts
Labels: feature, frontend

#34 [Feature] 메인 화면 헤더 디자인
  client/src/components/main/MainHeader.tsx
  client/src/constants/colors.ts
  client/src/index.tsx
  client/src/styles/reset.css
Labels: frontend, UI/CSS

#36 [Feature] 실시간 채팅 구현
  client/src/App.tsx
  client/src/api/index.ts
  client/src/index.tsx
  client/src/pages/Category.tsx
  client/src/pages/Chat.tsx
  client/src/pages/Home.tsx
  client/src/pages/Login.tsx
  client/src/recoil/atoms/user.ts
  client/src/styles/reset.css
  client/src/types/index.ts
  server/sql/init.sql
  server/src/app.module.ts
  server/src/chat/chat.controller.ts
  server/src/chat/chat.service.ts
  server/src/login/login.controller.ts
  server/src/login/login.module.ts
  server/src/login/login.service.ts
  server/src/product/entities/product.entity.ts
  server/src/product/product.service.ts
  server/src/social-login/social-login.controller.ts
  server/src/social-login/social-login.service.ts
  server/src/user/user.controller.ts
  server/src/user/user.service.ts
  server/src/utils/chat.ts
  server/src/utils/session.ts
Labels: feature, frontend, backend

#43 [Feature] 로그아웃 API 구현
  client/src/api/index.ts
  client/src/pages/Profile.tsx
  server/src/app.module.ts
  server/src/logout/logout.controller.ts
  server/src/logout/logout.module.ts
  server/src/logout/logout.service.ts
  server/src/utils/session.ts
Labels: feature, backend

#47 [Feature] 공통 헤더 및 프로필, 로그인 페이지 디자인
  client/public/index.html
  client/src/assets/icons/github.svg
  client/src/assets/icons/index.ts
  client/src/components/common/Button.tsx
  client/src/components/common/Header.tsx
  client/src/components/common/Layout.tsx
  client/src/pages/Login.tsx
  client/src/pages/Profile.tsx
  client/src/styles/reset.css
Labels: feature, refactoring, UI/CSS

#44 [Feature] 페이지 애니메이션 구현
  client/src/App.tsx
  client/src/components/Slider/PageSlider.tsx
  client/src/components/Slider/TransitionLayout.tsx
  client/src/components/main/MainHeader.tsx
  client/src/constants/sliderPosition.ts
  client/src/pages/Category.tsx
  client/src/pages/Chat.tsx
  client/src/pages/Product.tsx
Labels: feature, frontend

#48 [Refactor] onClick 콜백 함수 분리
  client/src/pages/Login.tsx
  client/src/pages/Profile.tsx
Labels: frontend, refactoring

#49 [Feature] 카테고리 페이지, 상품 목록 디자인
  client/src/App.tsx
  client/src/components/ProductItem.tsx
  client/src/components/Slider/TransitionLayout.tsx
  client/src/components/common/Button.tsx
  client/src/components/common/Header.tsx
  client/src/components/common/Layout.tsx
  client/src/components/main/MainHeader.tsx
  client/src/constants/colors.ts
  client/src/constants/sizes.ts
  client/src/pages/Category.tsx
  client/src/pages/Home.tsx
  client/src/pages/Login.tsx
  client/src/recoil/atoms/category.ts
  client/src/styles/reset.css
  client/src/types/index.ts
  client/src/utils/date.ts
  server/src/app.module.ts
  server/src/product/entities/product.entity.ts
  server/src/product/product.service.ts
Labels: feature, frontend, UI/CSS

#50 [UI/CSS] 내 동네 페이지 디자인
  client/src/components/main/MainHeader.tsx
  client/src/components/region/RegionInputModal.tsx
  client/src/components/region/RegionSelectModal.tsx
  client/src/pages/Region.tsx
Labels: feature, frontend, UI/CSS

#53 [Feature] 내 동네 설정하기 페이지 완성
  client/src/api/index.ts
  client/src/components/common/Alert.tsx
  client/src/components/main/MainHeader.tsx
  client/src/components/region/RegionInputModal.tsx
  client/src/components/region/RegionSelectModal.tsx
  client/src/hooks/useUserRegionState.ts
  client/src/pages/Region.tsx
  client/src/styles/reset.css
  client/src/types/index.ts
  server/src/product/product.service.ts
  server/src/region/region.controller.ts
  server/src/region/region.service.ts
  server/src/social-login/social-login.controller.ts
  server/src/social-login/social-login.module.ts
  server/src/social-login/social-login.service.ts
  server/src/user/entities/user-region.entity.ts
  server/src/user/user.controller.ts
  server/src/user/user.service.ts
Labels: feature, frontend

#51 [Feature] 글쓰기, 상품 상세 페이지
  client/src/App.tsx
  client/src/components/common/Header.tsx
  client/src/components/common/Layout.tsx
  client/src/components/hooks/useCategories.tsx
  client/src/constants/sizes.ts
  client/src/pages/Category.tsx
  client/src/pages/Home.tsx
  client/src/pages/MyPage.tsx
  client/src/pages/Product.tsx
  client/src/pages/Write.tsx
  client/src/types/index.ts
  server/src/product/entities/product.entity.ts
  server/src/product/product.service.ts
Labels: feature, frontend, UI/CSS

#56 [Bug] user.userRegions의 옵셔널체이닝 문법으로 인한 에러 해결
  client/src/components/region/RegionSelectModal.tsx
  client/src/hooks/useUserRegionState.ts
Labels: bugfix

#58 [Refactor] tempUserId 제거 colors 상수 대문자로 변경
  client/src/components/common/Alert.tsx
  client/src/components/region/RegionInputModal.tsx
  client/src/components/region/RegionSelectModal.tsx
  client/src/pages/Region.tsx
  server/src/chat/chat.service.ts
  server/src/product/product.service.ts
Labels: refactoring

#61 [Bugfix] 유저의 userRegion 값이 없는 버그 수정
  server/src/login/login.service.ts
Labels: bugfix, backend

#62 [Feature] 글쓰기페이지에 카테고리 영역 모달로 분리 및 지역 표시
  client/src/components/common/Alert.tsx
  client/src/components/common/Modal.tsx
  client/src/components/region/RegionInputModal.tsx
  client/src/components/write/categoryModal.tsx
  client/src/hooks/useUserRegionState.ts
  client/src/pages/Home.tsx
  client/src/pages/Region.tsx
  client/src/pages/Write.tsx
  client/src/styles/reset.css
  client/src/types/dto.ts
Labels: feature, frontend

#64 [Feature] S3 이미지 업로드
  client/src/api/aws.ts
  client/src/api/index.ts
  client/src/components/ProductItem.tsx
  client/src/components/common/ImageUploader.tsx
  client/src/pages/Write.tsx
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/aws/aws.controller.ts
  server/src/aws/aws.module.ts
  server/src/aws/aws.service.ts
Labels: feature, frontend, backend

#68 [Hotfix ] write 페이지에 중복함수 제거
  client/src/pages/Write.tsx
  client/src/types/dto.ts
Labels: bugfix

#72 [Deploy] 깃헙 액션 deploy 파일 추가
  .github/workflows/deploy.yml
Labels: setup, pair

#69 [Feature] 채팅 페이지 기능 및 디자인
  client/src/App.tsx
  client/src/api/index.ts
  client/src/components/ProductItem.tsx
  client/src/components/chat/ChatContent.tsx
  client/src/components/chat/ChatForm.tsx
  client/src/components/chat/ProductInfo.tsx
  client/src/components/common/ProductImage.tsx
  client/src/constants/sizes.ts
  client/src/pages/Chat.tsx
  client/src/pages/ChatContent.tsx
  client/src/pages/ChatDetail.tsx
  client/src/pages/Product.tsx
  client/src/types/index.ts
  server/src/chat/chat.controller.ts
  server/src/chat/chat.service.ts
  server/src/chat/dto/create-chat-room.dto.ts
  server/src/chat/entities/chat-room.entity.ts
  server/src/login/login.controller.ts
  server/src/login/login.service.ts
  server/src/main.ts
  server/src/product/entities/product.entity.ts
  server/src/product/product.service.ts
  server/src/social-login/social-login.controller.ts
  server/src/social-login/social-login.service.ts
  server/src/user/entities/user.entity.ts
  server/src/user/user.service.ts
Labels: feature, frontend, refactoring, UI/CSS, backend

#75 [Feature] 좋아요 기능 구현
  client/src/App.tsx
  client/src/components/common/LikeButton.tsx
  client/src/components/common/ProductItemWrapper.tsx
  client/src/components/main/MainHeader.tsx
  server/src/app.module.ts
  server/src/social-login/social-login.controller.ts
Labels: feature, frontend

#77 [Feature] 카테고리 검색
  client/src/api/index.ts
  client/src/components/common/LikeButton.tsx
  client/src/components/common/ProductItemWrapper.tsx
  client/src/components/main/MainHeader.tsx
  client/src/pages/Home.tsx
  server/src/product/product.controller.ts
  server/src/product/product.service.ts
Labels: feature, frontend, backend

#78 [Feature] 채팅 나가기
  client/src/api/index.ts
  client/src/components/chat/ChatLeaveModal.tsx
  client/src/components/common/Modal.tsx
  client/src/components/common/ProductImage.tsx
  client/src/components/common/ProductItem.tsx
  client/src/constants/image.ts
  client/src/pages/Chat.tsx
  client/src/pages/ChatDetail.tsx
  server/src/chat/chat.controller.ts
  server/src/chat/chat.service.ts
  server/src/utils/chat.ts
Labels: feature, frontend, backend

#83 [UI/CSS] UI/CSS 수정
  client/src/components/Slider/TransitionLayout.tsx
  client/src/components/Unauthorized.tsx
  client/src/components/chat/ChatContent.tsx
  client/src/components/chat/ChatForm.tsx
  client/src/components/common/Header.tsx
  client/src/components/common/ImageUploader.tsx
  client/src/components/common/Modal.tsx
  client/src/components/common/ProductItem.tsx
  client/src/components/main/MainHeader.tsx
  client/src/components/region/RegionSelectModal.tsx
  client/src/pages/MyPage.tsx
  client/src/pages/Product.tsx
  client/src/pages/Profile.tsx
  client/src/pages/Region.tsx
  client/src/pages/Write.tsx
  client/src/styles/common.ts
Labels: UI/CSS

#88 [Feature] 마이 페이지 채팅 & 읽지 않은 메시지
  client/src/api/index.ts
  client/src/components/common/ChatList.tsx
  client/src/components/common/Header.tsx
  client/src/components/menu/Chat.tsx
  client/src/constants/myPageTab.ts
  client/src/pages/Chat.tsx
  client/src/pages/ChatDetail.tsx
  client/src/pages/MyPage.tsx
  client/src/recoil/atoms/myPageTab.ts
  client/src/utils/date.ts
  server/src/chat/chat.controller.ts
  server/src/chat/chat.service.ts
  server/src/chat/entities/chat-room.entity.ts
Labels: feature, frontend, backend

#89 [Feature] 카테고리 이미지 추가
  client/src/pages/Category.tsx
  server/sql/init.sql
Labels: db, feature, frontend

#93 [Feature] 내 동네 등록에 위치기반 검색 추가
  client/public/index.html
  client/src/components/common/Loading.tsx
  client/src/components/common/ProductSkeleton.tsx
  client/src/components/region/RegionInputModal.tsx
  client/src/react-app-env.d.ts
  client/src/types/index.ts
  client/src/utils/location.ts
Labels: frontend

#95 [UI/CSS] CSS 디테일 수정
  client/src/components/common/ProductItem.tsx
  client/src/components/common/ProductItemWrapper.tsx
  client/src/components/common/ProductSkeleton.tsx
  client/src/components/main/MainHeader.tsx
  client/src/components/region/RegionSelectModal.tsx
  client/src/pages/Category.tsx
  client/src/pages/Home.tsx
  client/src/pages/MyPage.tsx
  client/src/pages/Product.tsx
  client/src/styles/ProductLayouts.ts
  client/src/styles/common.ts
  client/src/styles/reset.css
  client/src/styles/skeletonItem.ts
Labels: UI/CSS, pair

#96 [BugFix] 파일 이름 수정
  client/src/components/common/ProductSkeleton.tsx
Labels: bugfix

#97 [BugFix] 파일 이름 대소문자 수정
  client/src/styles/productLayouts.ts
Labels: bugfix

#101 [Feature] 이미지 다중업로드 기능 추가 및 업로드시 로딩표시 추가
  client/src/api/index.ts
  client/src/components/common/ImageLoading.tsx
  client/src/components/common/ImageUploader.tsx
  client/src/components/common/Loading.tsx
  client/src/pages/MyPage.tsx
  client/src/types/index.ts
  server/src/aws/aws.controller.ts
  server/src/aws/aws.service.ts
Labels: feature, frontend, backend

#102 [Feature] 채팅방에 들어가있을 때도 메시지 읽음으로 처리
  client/src/api/index.ts
  client/src/pages/ChatDetail.tsx
  server/src/chat/chat.controller.ts
  server/src/chat/chat.service.ts
Labels: feature, frontend, backend

#104 [Feature] 상품 수정하기 삭제하기 기능 추가
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/api/index.ts
  client/src/components/common/DropDown.tsx
  client/src/components/common/ProductItemWrapper.tsx
  client/src/components/common/SwipeImage.tsx
  client/src/components/product/ProductHeaderButton.tsx
  client/src/components/write/ProductDeleteModal.tsx
  client/src/components/write/categoryModal.tsx
  client/src/pages/Product.tsx
  client/src/pages/Write.tsx
  client/src/types/index.ts
  server/src/product/entities/product-image.entity.ts
  server/src/product/product.service.ts
Labels: feature, frontend

#111 [Feature] 시작하기 페이지 추가 & 버그 수정
  client/public/index.html
  client/src/App.tsx
  client/src/components/Unauthorized.tsx
  client/src/components/auth/EmptyRegion.tsx
  client/src/components/auth/Unauthorized.tsx
  client/src/components/chat/ProductInfo.tsx
  client/src/components/common/Button.tsx
  client/src/components/common/ChatList.tsx
  client/src/components/common/FormattedPrice.tsx
  client/src/components/common/ProductItem.tsx
  client/src/components/region/RegionSelect.tsx
  client/src/hooks/useUserRegionState.ts
  client/src/pages/ChatDetail.tsx
  client/src/pages/Login.tsx
  client/src/pages/MyPage.tsx
  client/src/pages/Product.tsx
  client/src/pages/Region.tsx
  client/src/pages/Start.tsx
  client/src/pages/Write.tsx
  server/src/category/entities/category.entity.ts
  server/src/product/entities/product-image.entity.ts
  server/src/product/entities/product.entity.ts
  server/src/region/entities/region.entity.ts
  server/src/social-login/social-login.service.ts
  server/src/user/entities/user-region.entity.ts
  server/src/user/entities/user.entity.ts
Labels: bugfix, feature, frontend, backend

#112 [Feature] 상품목록 필터링 기능 추가
  client/src/api/index.ts
  client/src/components/common/ProductItemWrapper.tsx
  client/src/components/hooks/useInfiniteScroll.ts
  client/src/pages/Category.tsx
  client/src/recoil/atoms/user.ts
  server/src/product/product.controller.ts
  server/src/product/product.service.ts
Labels: feature, frontend, pair

#113 [BugFix] myPage에서 탭 선택시, 상품목록 업데이트 안되는 버그해결
  client/src/components/common/ProductItemWrapper.tsx
  client/src/pages/MyPage.tsx
Labels: bugfix

#114 [Feature] 상품 조회수 기능 추가
  server/src/product/product.service.ts
Labels: feature, backend

#116 [Feature] 동네 이름 추가
  client/src/components/common/ProductItem.tsx
  client/src/components/region/RegionSelect.tsx
  client/src/components/region/RegionSelectModal.tsx
  client/src/hooks/useUserRegionState.ts
  client/src/utils/region.ts
  server/sql/init.sql
  server/src/app.module.ts
Labels: feature, frontend

#119 [Feature] 채팅 기능 개선 및 버그 수정
  client/src/components/chat/ChatContent.tsx
  client/src/components/chat/ChatContents.tsx
  client/src/components/region/RegionInputModal.tsx
  client/src/components/region/RegionSelect.tsx
  client/src/constants/sizes.ts
  client/src/pages/ChatDetail.tsx
  client/src/pages/MyPage.tsx
  client/src/utils/date.ts
  server/src/chat/entities/chat-content.entity.ts
Labels: feature, frontend, UI/CSS

#118 [Feature] 상품상세페이지에서 상태 변경기능 추가 및 상품보기화면에 표출 방법 변경
  client/src/api/index.ts
  client/src/assets/icons/index.ts
  client/src/components/common/DropDownModal.tsx
  client/src/components/common/ProductItem.tsx
  client/src/components/product/ProductStatusButton.tsx
  client/src/constants/colors.ts
  client/src/constants/sizes.ts
  client/src/enum/status.enum.ts
  client/src/pages/Product.tsx
  client/src/types/index.ts
  server/src/product/product.controller.ts
  server/src/product/product.service.ts
Labels: feature, frontend, backend

#122 [Feature] 스와이퍼 이미지 선택 시 확대
  client/src/components/common/Modal.tsx
  client/src/components/common/SwipeImage.tsx
  client/src/pages/Product.tsx
Labels: feature, frontend

#125 [Feature] Reverse geocoding 적용 및 카카오 API 제거
  client/public/index.html
  client/src/api/index.ts
  client/src/components/region/RegionInputModal.tsx
  client/src/react-app-env.d.ts
  client/src/types/index.ts
  client/src/utils/location.ts
  server/src/region/region.controller.ts
  server/src/region/region.service.ts
Labels: feature, frontend, refactoring, backend

#128 [Feature] 카테고리, 나눔, 채팅방 디자인 및 버그 수정
  client/src/components/chat/ChatContents.tsx
  client/src/components/chat/ProductInfo.tsx
  client/src/components/common/ChatList.tsx
  client/src/components/common/FormattedPrice.tsx
  client/src/components/main/MainHeader.tsx
  client/src/components/region/RegionSelect.tsx
  client/src/constants/sizes.ts
  client/src/pages/ChatDetail.tsx
  client/src/pages/Product.tsx
Labels: feature, frontend, UI/CSS

#130 [BugFix] 충돌 해결하면서 생긴 버그 수정
  client/src/pages/Product.tsx
Labels: bugfix

#132 [BugFix] 상품 상세 이미지 캐러셀 안 보이는 버그 해결
  client/src/components/common/SwipeImage.tsx
Labels: bugfix

#133 [UI/CSS] 상품 내용 줄바꿈 적용
  client/src/pages/Category.tsx
  client/src/pages/Product.tsx
Labels: UI/CSS

#134 [Bugfix] 상품 삭제 안 되는 버그 해결
  client/src/components/common/ProductItem.tsx
Labels: bugfix

#135 [BugFix] 채팅 날짜 수정
  client/src/components/region/RegionInputModal.tsx
  client/src/pages/Write.tsx
  client/src/utils/date.ts
Labels: bugfix
